title: Mathematics for AI
description: Course website and materials for Mathematics for AI

remote_theme: just-the-docs/just-the-docs

plugins:
  - jekyll-remote-theme

url: "https://yding2.github.io"
baseurl: "/math-for-ai"

color_scheme: light
